routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', 'UserPagesController@welcome')->name('welcome');
Route::get('/teams/{story}', 'UserPagesController@teams');

Auth::routes(['verify'=>true]);

Route::group(['prefix' => 'user','middleware'=>['roles','verified'],'roles'=>['admins','users']], function () {


    Route::get('/profile/{id}','UserPagesController@profile');
    Route::get('/profile/{id}/edit','UserPagesController@profileedit');
    Route::put('/profile/{id}','UserPagesController@profileupdate');
    Route::get('/team/{id}','UserPagesController@myteam');
    Route::get('/changepass/{id}/edit','UserPagesController@editpass');
    Route::put('/changepass/{id}','UserPagesController@updatePassword');
    Route::delete('/teamsusers/{teamId}/{userID}','TeamUserController@deleteTeamUser');
    Route::put('/teamsusers/{teamId}/{userID}','TeamUserController@addTeamUser');
    Route::get('/team/{id}/edit','TeamController@editdata');
    Route::put('/team/{id}','TeamController@updatedata');
    Route::delete('/team/{team}','TeamController@delete');
    Route::put('/money/{user?}','MoneyController@store');
    Route::name('user.')->group( function () {

        Route::resource('stories','UserPagesController')->only(['show','store','edit','update','create']);

    });
    Route::resource('novel','NovelPagesController')->only(['show','index']);

});

Route::group(['prefix' => 'admin','middleware'=>'roles','roles'=>'admins'], function () {

    Route::resource('novels','NavelController');
    Route::get('/changepass/{id}/edit','AdminUsersController@editpass');
    Route::put('/changepass/{id}','AdminUsersController@updatePassword');
    Route::delete('/teamsusers/{teamId}/{userID}','TeamUserController@deleteTeamUser');
    Route::put('/teamsusers/{teamId}/{userID}','TeamUserController@addTeamUser');
    Route::put('/rank/{teamId}/{userID}','TeamController@updaterank');
    Route::put('/unrank/{teamId}/{userID}','TeamController@updateunrank');
    Route::get('/reports','AdminUsersController@teamdata');
    Route::put('/done/{userid}','UserPagesController@changedone');
    Route::put('users/Active/{user}','UserPagesController@activeUser')->name('activeUser');

    Route::post('users/{user}/addMoney', 'AdminUsersController@addMoney')->name('addUserMoney');
    Route::post('users/{user}/delMoney', 'AdminUsersController@delMoney')->name('delUserMoney');
    Route::post('users/{user}/payMoney', 'AdminUsersController@payMoney')->name('payUserMoney');
    Route::get('/money','MoneyController@index')->name('money');
    Route::put('/money/{money}','MoneyController@update');
    Route::delete('/money/{money}','MoneyController@delete')->name('delMoney');
    Route::post('users/Month', 'AdminUsersController@usersMonth')->name('users.Month');
    Route::post('users/{user}/Month', 'AdminUsersController@userMonth')->name('users.user.Month');

    Route::resource('users','AdminUsersController');
    Route::resource('novels','NavelController');
    Route::resource('pays','PayController');
    Route::resource('contacts','ContactController');
    Route::resource('teams','TeamController');
    Route::resource('stories','StoryController');
});
/*
 * index  : Show All Data (GET)
 * create : Show create View (GET)
 * store  : Save data in database (POST)
 * show   : show one data (GET)
 * edit   : show one data for edit  (GET)
 * update : update data and redirect (PUT || PATCH)
 * destroy: Delete Data From database (DELETE)
 *
 * */

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Spatie\Activitylog\Traits\LogsActivity;

class User extends Authenticatable implements MustVerifyEmail{
    use Notifiable;
    use LogsActivity;
    protected static $logOnlyDirty = true;

    protected $fillable = [
        'name', 'email', 'password','paymoney','contact_id','contact','pay_id','email_verified_at'
    ];


    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function pay(){ return $this->belongsTo(Pay::class)->withDefault([
        "name"=>"no Pay way"
    ]); }

    public function cont(){ return $this->belongsTo(Contact::class); }
    public function contact(){ return $this->belongsTo(Contact::class)->withDefault([
        "name"=>"no Contact way"
    ]); }

    public function mymoney(){ return $this->hasMany(Money::class); }

    public function teams() { return $this->belongsToMany(Team::class)->withTimestamps(); }

    public function stories() { return $this->hasMany(Story::class); }


    public function roles(){ return $this->belongsToMany(Role::class); }

    public function hasAnyRole($roles){
        if (is_array($roles)){
            foreach ($roles as $role){
                if ($this->hasRole($role)){ return true; }
            }
        }else{
            if ($this->hasRole($roles)){
                return true;
            }
        }
        return false;
    }

    public function hasRole($role){
        if ($this->roles()->where('name',$role)->first()){
            return true;
        }
        return false;
    }

    /**
     * @return mixed
     */
    public function storiesMoney(){

        return $this->stories()->where('case',0)->with('navel')->get()->sum('navel.price');
    }

    public function myAllMoney(){ return $this->mymoney()->where('case',0)->sum('money'); }
    public function oldMoney(){ return $this->mymoney()->where('case',1)->sum('money'); }
    public function moneyMonth(){ return $this->mymoney()->where('case',3)->sum('money'); }
    public function newMoney(){ return $this->mymoney()->where('case',4)->sum('money'); }

    public function GivenMoney(){ return $this->mymoney()->sum('money'); }


    public function userMonth()
    {
        DB::transaction(function (){
            $counter=$this->storiesMoney();
            if ($counter!==0){
                Money::create([
                    'user_id'=>$this->id,
                    'money'=>$counter,
                    'case'=>3
                ]);
            }
            $this->stories()->update(['case' => 1]);
            $this->mymoney()->where('case',4)->update(['case'=>3]);
        });
    }
}

resources/views/users/create.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>اضافه مستخدم</h1>
@stop

@section('content')
    <form method="POST" action="{{ route('users.store') }}">
        @csrf
            <div class="form-group row">
                <label for="name" class="col-md-3 col-form-label text-md-right">{{ __('name') }}</label>

                <div class="col-md-6">
                    <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required autofocus>

                    @if ($errors->has('name'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="email" class="col-md-3 col-form-label text-md-right">{{ __('Email') }}</label>

                <div class="col-md-6">
                    <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required>

                    @if ($errors->has('email'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('email') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="name" class="col-md-3 col-form-label text-md-right">{{ __('How To Contact') }}</label>

                <div class="col-md-6">
                    <select class="form-control{{ $errors->has('contact_id') ? ' is-invalid' : '' }}" name="contact_id"  value="{{ old('contact_id') }}" id="contact_id">
                        @foreach (\App\Contact::all() as $contact)
                            <option value="{{$contact->id}}">{{$contact->name}}</option>
                        @endforeach
                    </select>
                    @if ($errors->has('contact'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('contact') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
        <div class="form-group row">
            <label for="name" class="col-md-3 col-form-label text-md-right">{{ __('Contact') }}</label>
            <div class="col-md-6">
                <input id="contact" type="text" class="form-control{{ $errors->has('contact') ? ' is-invalid' : '' }}" name="contact" value="{{ old('contact') }}" required>
            </div>
        </div>

            <div class="form-group row">
                <label for="name" class="col-md-3 col-form-label text-md-right">{{ __('How To Pay') }}</label>

                <div class="col-md-6">
                    <select class="form-control{{ $errors->has('pay_id') ? ' is-invalid' : '' }}" name="pay_id"  value="{{ old('pay_id') }}" id="pay_id">
                        @foreach (\App\Pay::all() as $contact)
                            <option value="{{$contact->id}}">{{$contact->name}}</option>
                        @endforeach
                    </select>
                    @if ($errors->has('name'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('contact') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

        <div class="form-group row">
            <label for="name" class="col-md-3 col-form-label text-md-right">{{ __('Pay') }}</label>

            <div class="col-md-6">
                <input id="contact" type="text" class="form-control{{ $errors->has('paymoney') ? ' is-invalid' : '' }}" name="paymoney" value="{{ old('paymoney') }}" required >
            </div>
        </div>

        <div class="form-group row">
                <label for="password" class="col-md-3 col-form-label text-md-right">{{ __('Password') }}</label>

                <div class="col-md-6">
                    <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>
                    @if ($errors->has('password'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('password') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="password-confirm" class="col-md-3 col-form-label text-md-right">{{ __('Password confirm') }}</label>

                <div class="col-md-6">
                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                </div>
            </div>

            <div class="form-group row mb-0">
                <label for="" class="col-md-5"></label>
                <div class="col-md-6">
                    <button type="submit" class="btn btn-primary">
                        {{ __('Register') }}
                    </button>
                </div>
            </div>
    </form>
@stop

resources/views/users/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>تعديل المستخدم</h1>
@stop

@section('content')
    @include('errors')

    <form action="{{url('admin/users/'.$user->id)}}" method="POST" role="form" >
        @csrf
        @method('PUT')

        <div class="form-group">
            <div class="col-md-4">
                <label for="name">الاسم</label>
            </div>
            <div class="col-md-6">
                <input type="text" name="name" value="{{$user->name}}" id="name" class="form-control" placeholder="الاسم" aria-describedby="name">
                <br>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-4">
                <label for="email">البريد الالكتروني</label>
            </div>
            <div class="col-md-6">
                <input type="email" name="email" value="{{$user->email}}" id="email" class="form-control" placeholder="البريد الالكتروني" aria-describedby="email">
                <br>
            </div>
        </div>

        <div class="form-group row">
            <label for="name" class="col-md-4">كيف تريد طريقة التواصل ؟</label>

            <div class="col-md-6">
                <select class="form-control{{ $errors->has('contact_id') ? ' is-invalid' : '' }}" name="contact_id"  value="{{ old('contact_id') }}" id="contact_id">
                    @foreach (\App\Contact::all() as $contact)
                        <option value="{{$contact->id}}" {{($contact->id==$user->contact_id)?'selected':''}} >{{$contact->name}}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="form-group row">
            <label for="name" class="col-md-4">طريقة التواصل</label>
            <div class="col-md-6">
                <textarea name="contact" class="form-control w-100" required>{{ $user->contact }}</textarea>
            </div>
        </div>

        <div class="form-group row">
            <label for="name" class="col-md-4">كيف تريد الدفع ؟</label>
            <div class="col-md-6">
                <select class="form-control" name="pay_id"  id="pay_id">
                    @foreach (\App\Pay::all() as $pay)
                        <option value="{{$pay->id}}" {{($pay->id==$user->contact_id)?'selected':''}}>{{$pay->name}}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="form-group row">
            <label for="name" class="col-md-4 col-form-label text-md-right">طريقة الدفع</label>
            <div class="col-md-6">
                <textarea name="paymoney" class="form-control w-100" required>{{$user->paymoney}}</textarea>
            </div>
        </div>


        <button type="submit" class="btn btn-warning">تعديل المستخدم</button>
    </form>

@stop

resources/views/users/pass.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Edit User Password</h1>
@stop

@section('content')
    <form action="{{url('admin/changepass/'.$user->id)}}" method="POST" role="form">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="password">Enter new pass</label>
            <input required type="password" name="password" id="name" class="form-control" placeholder="password" aria-describedby="password">
        </div>
        <button type="submit" class="btn btn-warning">Edit Password</button>
    </form>

@stop

resources/views/users/user.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1 class="text-center font-weight-bold text-muted">{{optional($user)->name}}</h1>
@stop
@section('content')
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">{{optional($user)->name}}</h3>
            <div class="box-tools pull-right">

                <a href="{{url('admin/changepass/'.optional($user)->id.'/edit')}}" class="btn btn-primary">تغير كلمه السر</a>
                <a href="{{url('admin/users/'.optional($user)->id.'/edit')}}" class="btn btn-warning">تحديث</a>

                <label for="#">
                    <form action="{{url('admin/users/'.optional($user)->id)}}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger">حذف</button>
                    </form>
                </label>

            </div>
            <!-- /.box-tools -->
        </div>
        <div class="box-body">
            الاسم :  {{optional($user)->name}}<br>
            البريد الالكتروني : {{optional($user)->email}}<br>
            @if ($pay)
                الدفع بواسطة :{{optional($pay)->name}}({{optional($user)->paymoney}})<br>
            @endif
            @if ($contact)
                التواصل عن طريق : {{optional($contact)->name}} ({{optional($user)->contact}}) <br>
            @endif
        </div>

    </div>



    <div class="col-md-4">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">الفصول</h3>
                <div class="box-tools pull-right"></div>
            </div>
                <div class="box-body">

                    @if (count(optional($user)->stories)>0)
                        <ul class="list-unstyled"  style="max-height:200px;overflow: hidden;overflow-y: auto;">
                            @foreach (optional($user)->stories()->orderBy('storynum','DESC')->get() as $stroy)
                                <li><a href="{{url('admin/stories/'.$stroy->id)}}">{{$stroy->storynum}} -  {{$stroy->title}}</a></li>
                            @endforeach
                        </ul>
                    @else
                        {{"لا ينتمي الي اي فريق"}}
                    @endif
                </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="box box-warning">
            <div class="box-header with-border">
                <h3 class="box-title">الفرق</h3>
                <div class="box-tools pull-right"></div>
            </div>
                <div class="box-body">
                    @if (count(optional($user)->teams)>0)
                        <ul class="list-unstyled scrolH">
                            @foreach (optional($user)->teams as $team)
                                <li><a href="{{url('admin/teams/'.optional($team)->id)}}">{{optional($team)->name}}</a></li>
                            @endforeach
                        </ul>
                        @else
                        {{"لا يوجد فصول"}}
                    @endif
                </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="box box-success">
            <div class="box-header with-border">
                <h3 class="box-title"><i class="fa fa-usd" aria-hidden="true"></i> حوافز</h3>
                <div class="box-tools pull-right"></div>
            </div>
            <div class="box-body">
                <form action="{{route('addUserMoney',optional($user)->id)}}" method="POST">
                    @csrf
                    <input class="form-control" type="number" step="any" placeholder="المبلغ" name="moneyUser">
                    <hr>
                    <button class="btn btn-success" type="submit">اضافة حافز</button>
                </form>
            </div>
        </div>
    </div>

    <div class="clearfix"></div>

    <div class="col-md-3 col-sm-6 col-xs-12">

        <div class="info-box bg-green text-white col-md-3">
            <span class="info-box-icon"><i class="fa fa-usd"></i></span>
            <div class="info-box-content">
                <span class="info-box-text">مستحقات تم استلامها</span>
                <span class="info-box-number">{{$lastMoney}}$</span>

            </div><!-- /.info-box-content -->
        </div><!-- /.info-box -->
    </div>



    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box bg-red col-md-3">
            <span class="info-box-icon"><i class="fa fa-usd"></i></span>
            <div class="info-box-content">
                <span class="info-box-text">مستحقات تحت الطلب</span>
                <span class="info-box-number">{{$userMoney}}$</span>

            </div><!-- /.info-box-content -->
        </div><!-- /.info-box -->
    </div>



    <div class="col-md-3 col-sm-12 col-xs-12">
        <div class="info-box bg-light-blue-active col-md-3 ">
            <span class="info-box-icon"><i class="fa fa-usd"></i></span>
            <div class="info-box-content">
                <span class="info-box-text">مستحقات متراكمة</span>
                <span class="info-box-number">{{$monthMoney}}$</span>
            </div><!-- /.info-box-content -->
        </div><!-- /.info-box -->

    </div>

    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box bg-aqua col-md-3 ">
            <span class="info-box-icon"><i class="fa fa-usd"></i></span>
            <div class="info-box-content">
                <span class="info-box-text">مستحقات الشهر</span>
                <span class="info-box-number">{{$nowMoney}}$</span>
            </div><!-- /.info-box-content -->
        </div><!-- /.info-box -->

    </div>
    <div class="clearfix"></div>
    <div class="col-md-12">
        <div class="box box-success">

            <div class="box-header with-border">
                <h3 class="box-title"> تحويل الي مستحقات متراكمة </h3>
            </div>

            <div class="box-body">
                {!! Form::open(['route' => ['users.user.Month','user'=>optional($user)->id], 'method' => 'post']) !!}
                    <button class="btn btn-soundcloud"> تحويل مستحقات الشهر </button>
                {!! Form::close() !!}
            </div>
        </div>
    </div>

    <div class="clearfix"></div>

    <div class="col-md-12">
        <div class="box box-danger">
            <div class="box-header with-border">
                <h3 class="box-title">بيانات عملية الدفع</h3>
                <div class="box-tools pull-right"></div>
            </div>
            <div class="box-tools pull-left">
                <!-- Small modal -->
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-payUserMoney">دفع كل العمليات</button>

                <!-- Small modal -->
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target=".bs-delUserMoney">حذف كل العمليات</button>

                <div class="modal fade bs-delUserMoney" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                    <div class="modal-dialog modal-sm" role="document">
                        <div class="modal-content">
                            {!! Form::open(['route' => ['delUserMoney','user'=>optional($user)->id], 'method' => 'post']) !!}
                                <button class="btn btn-danger  pull-left">حذف كل العمليات</button>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>

                <div class="modal fade bs-payUserMoney" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                    <div class="modal-dialog modal-sm" role="document">
                        <div class="modal-content">

                            {!! Form::open(['route' => ['payUserMoney','user'=>optional($user)->id], 'method' => 'post']) !!}
                                <button class="btn btn-primary">دفع كل العمليات</button>
                            {!! Form::close() !!}

                        </div>
                    </div>
                </div>


                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
            <br>
            <div class="box-body scrolH">
                <table class="table-responsive table table-hover">
                    <tr>
                        <td>#</td>
                        <td>المبلغ</td>
                        <td>تاريخ طلب المبلغ</td>
                        <td>الحاله</td>
                        <td>دفع</td>
                        <td>حذف</td>
                    </tr>
                    @foreach ($detalisMoney as $key=> $des)
                    <tr>
                        <td>{{($key+1)}}</td>
                        <td>{{optional($des)->money}}</td>
                        <td>{{date_format(optional($des)->updated_at,'Y-m-d')}}</td>
                        <td>
                            @if (optional($des)->case==1)
                                <div class="text-success">
                                   <h4> تم الدفع</h4>
                                </div>
                            @else
                                <div class="text-danger">
                                    <h4>لم يتم الدفع</h4>
                                </div>
                            @endif
                        </td>
                        <td>
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-money{{$key+2}}" @if (optional($des)->case==1) disabled @endif > دفع</button>
                            <div class="modal fade bs-money{{$key+2}}" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                                <div class="modal-dialog modal-sm" role="document">
                                    <div class="modal-content" style="padding: 10px;">
                                        <form action="{{url('admin/money/'.optional($des)->id)}}" method="POST">
                                            @csrf
                                            @method('PUT')
                                            <h3>
                                                هل انت متاكد انك تريد دفع المستحقات بقيمة <br>
                                                {{optional($des)->money}}$
                                            </h3>
                                            <button type="submit" class="btn btn-success" @if (optional($des)->case==1) disabled @endif style="float: left;">دفع</button>
                                            <button type="button" class="btn btn-danger" style="float: right;" data-dismiss="modal">الغاء</button>
                                            <div class="clearfix"></div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </td>
                        <td>
                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target=".bs-del-money{{$key+5}}"> حذف</button>
                            <div class="modal fade bs-del-money{{$key+5}}" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                                <div class="modal-dialog modal-sm" role="document">
                                    <div class="modal-content" style="padding: 10px;">
                                        <form action="{{route('delMoney',optional($des)->id)}}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger" style="float: left;">حذف</button>
                                            <button type="button" class="btn btn-default" style="float: right;" data-dismiss="modal">الغاء</button>
                                            <div class="clearfix"></div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </table>
            </div>
        </div>
    </div>

    <div class="clearfix"></div>
    {{--<div class="col-md-12">--}}
        {{--<div class="box box-danger">--}}
            {{--<div class="box-header with-border">--}}
                {{--<h3 class="box-title">Title</h3>--}}
                {{--<div class="box-tools pull-right">Habib</div>--}}
            {{--</div>--}}
            {{--<div class="box-body">--}}
                {{--Body--}}
            {{--</div>--}}
        {{--</div>--}}
    {{--</div>--}}


@stop