routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', 'UserPagesController@welcome')->name('welcome');
Route::get('/teams/{story}', 'UserPagesController@teams');

Auth::routes(['verify'=>true]);

Route::group(['prefix' => 'user','middleware'=>['roles','verified'],'roles'=>['admins','users']], function () {


    Route::get('/profile/{id}','UserPagesController@profile');
    Route::get('/profile/{id}/edit','UserPagesController@profileedit');
    Route::put('/profile/{id}','UserPagesController@profileupdate');
    Route::get('/team/{id}','UserPagesController@myteam');
    Route::get('/changepass/{id}/edit','UserPagesController@editpass');
    Route::put('/changepass/{id}','UserPagesController@updatePassword');
    Route::delete('/teamsusers/{teamId}/{userID}','TeamUserController@deleteTeamUser');
    Route::put('/teamsusers/{teamId}/{userID}','TeamUserController@addTeamUser');
    Route::get('/team/{id}/edit','TeamController@editdata');
    Route::put('/team/{id}','TeamController@updatedata');
    Route::delete('/team/{team}','TeamController@delete');
    Route::put('/money/{user?}','MoneyController@store');
    Route::name('user.')->group( function () {

        Route::resource('stories','UserPagesController')->only(['show','store','edit','update','create']);

    });
    Route::resource('novel','NovelPagesController')->only(['show','index']);

});

Route::group(['prefix' => 'admin','middleware'=>'roles','roles'=>'admins'], function () {

    Route::resource('novels','NavelController');
    Route::get('/changepass/{id}/edit','AdminUsersController@editpass');
    Route::put('/changepass/{id}','AdminUsersController@updatePassword');
    Route::delete('/teamsusers/{teamId}/{userID}','TeamUserController@deleteTeamUser');
    Route::put('/teamsusers/{teamId}/{userID}','TeamUserController@addTeamUser');
    Route::put('/rank/{teamId}/{userID}','TeamController@updaterank');
    Route::put('/unrank/{teamId}/{userID}','TeamController@updateunrank');
    Route::get('/reports','AdminUsersController@teamdata');
    Route::put('/done/{userid}','UserPagesController@changedone');
    Route::put('users/Active/{user}','UserPagesController@activeUser')->name('activeUser');

    Route::post('users/{user}/addMoney', 'AdminUsersController@addMoney')->name('addUserMoney');
    Route::post('users/{user}/delMoney', 'AdminUsersController@delMoney')->name('delUserMoney');
    Route::post('users/{user}/payMoney', 'AdminUsersController@payMoney')->name('payUserMoney');
    Route::get('/money','MoneyController@index')->name('money');
    Route::put('/money/{money}','MoneyController@update');
    Route::delete('/money/{money}','MoneyController@delete')->name('delMoney');
    Route::post('users/Month', 'AdminUsersController@usersMonth')->name('users.Month');
    Route::post('users/{user}/Month', 'AdminUsersController@userMonth')->name('users.user.Month');

    Route::resource('users','AdminUsersController');
    Route::resource('novels','NavelController');
    Route::resource('pays','PayController');
    Route::resource('contacts','ContactController');
    Route::resource('teams','TeamController');
    Route::resource('stories','StoryController');
});
/*
 * index  : Show All Data (GET)
 * create : Show create View (GET)
 * store  : Save data in database (POST)
 * show   : show one data (GET)
 * edit   : show one data for edit  (GET)
 * update : update data and redirect (PUT || PATCH)
 * destroy: Delete Data From database (DELETE)
 *
 * */

resources/views/novel/create.blade.php
@extends('adminlte::page')

@section('content_header')
    <h1 class="text-center">انشاء رواية جديدة</h1>
@stop

@section('content')
    <form action="{{url('admin/novels')}}" method="POST" role="form" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label for="name">اسم الرواية</label>
            <input type="text" class="form-control" name="name" id="name" aria-describedby="helpId" placeholder="Novel Name">
        </div>
        <div class="form-group">
            <label for="name">سعر الرواية</label>
            <input type="number" step="any" class="form-control" name="price" id="price" aria-describedby="helpId" placeholder="Price">
        </div>
        <div class="form-group">
            <label for="">صورة الرواية</label>
            <input type="file" class="form-control-file" name="image" id="image" placeholder="" aria-describedby="fileHelpId">
        </div>
        <div class="form-group">
            <label for="">الفريق المسئول عن الرواية</label>
            <select class="form-control" name="team_id" id="team_id">
                @foreach ($teams as $team)
                    <option value="{{$team->id}}">{{$team->name}}</option>
                @endforeach
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Add Novel</button>
    </form>

@stop

resources/views/novel/edit.blade.php
@extends('adminlte::page')
@section('content_header')
    <h1>تعديل الرواية</h1>
@stop

@section('content')
    <form action="{{url('admin/novels/'.$novel->id)}}" method="POST" role="form" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="name">اسم الرواية</label>
            <input type="text" value="{{$novel->name}}" class="form-control" name="name" id="name" aria-describedby="helpId" placeholder="Novel Name">
        </div>
        <div class="form-group">
            <label for="name">سعر الرواية</label>
            <input type="number" value="{{$novel->price}}" step="any" class="form-control" name="price" id="price" aria-describedby="helpId" placeholder="Price">
        </div>
        <div class="form-group">
            <label for="">صورة الرواية</label>
            <input type="file" class="form-control-file" name="image" id="image" placeholder="" aria-describedby="fileHelpId">
            <img src="{{asset('uploads/Novel\\'.$novel->image)}}" width="150" height="150" alt="">
        </div>
        <div class="form-group">
            <label for="">الفريق المسئول عن الرواية</label>
            <select class="form-control" name="team_id" id="team_id">
                @foreach ($teams as $team)
                    <option value="{{$team->id}}" {{($novel->team_id == $team->id)?"selected":''}} >{{$team->name}}</option>
                @endforeach
            </select>
        </div>
        <button type="submit" class="btn btn-warning">تعديل الرواية</button>
    </form>

@stop

resources/views/novel/novel.blade.php
@extends('adminlte::page')
@section('content_header')

@stop
@section('content')

    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">اسم الرواية : {{$novel->name}}</h3>
                <div class="box-tools pull-right">
                    <a href="{{url('admin/novels/'.$novel->id.'/edit')}}" class="btn btn-warning">تعديل</a>

                    <label for="#">
                        <form action="{{url('admin/novels/'.$novel->id)}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger">حذف</button>
                        </form>
                    </label>
                </div>
            </div>
            <div class="box-body">
                الفريق المسؤل عن الرواية <br>
                <a href="{{url('admin/teams/'.$novel->team->id)}}">{{$novel->team->name}}</a>
                <br>
               سعر الفصل الواحد  <br> {{$novel->price}}$
            </div>
        </div>
    </div>
    
    <div class="col-md-6">
        <div class="box box-solid">
            <div class="box-header with-border">
                <h3 class="box-title">الفصول</h3>
                <div class="box-tools pull-right"></div>
            </div>
            <div class="box-body">
                @if (count($novel->stories)>0)
                    <ul class="scrolH">
                        @foreach ($novel->stories()->orderBy('storynum','DESC')->paginate(15) as $story)
                            <li style="border-bottom: 1px solid #3f3f3f">
                                <a href="{{url('admin/stories/'.$story->id)}}" class="pull-right">{{$story->storynum}} - {{$story->title}}</a>
                                <a href="{{route('users.show',$story->user->id)}}" class="pull-left" >{{$story->user->name}}</a>
                            </li>
                        @endforeach
                    </ul>
                    @else
                    {{'لا يوجد فصول حتي الان'}}
                @endif
            </div>
        </div>
    </div>

@stop

resources/views/novel/show.blade.php
@extends('adminlte::page')
@section('content_header')
    <h1>عرض الروايات</h1>
@stop
@section('content')
    <div class="col-md-12">
        <div class="box box-solid">
            <div class="box-header with-border">
                <div class="box-tools pull-right">

                    <a href="{{url('admin/novels/create')}}" class="label label-primary">اضافة رواية</a>
                </div>
                </div>
                <div class="box-body">
                    @if ($novels->count()>0)
                        <table class="table table-responsive">
                            <tr style="border: none">
                                <th>#</th>
                                <th>اسم الرواية</th>
                                <th>صورة الرواية</th>
                                <th>عدد فصول الرواية</th>
                            </tr>
                            @foreach ($novels as $novel)
                                <tr>
                                    <td>{{$novel->id}}</td>
                                    <td><a href="{{route('novels.show',$novel->id)}}">{{$novel->name}}</a></td>
                                    <td><img src="{{asset('uploads/Novel/'.$novel->image)}}" width="50px" height="50px" alt=""></td>
                                    <td>{{count($novel->stories)}}</td>
                                </tr>
                            @endforeach
                        </table>
                        {{$novels->links()}}
                    @endif
                </div>
            </div>
        </div>
    </div>
@stop