routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', 'UserPagesController@welcome')->name('welcome');
Route::get('/teams/{story}', 'UserPagesController@teams');

Auth::routes(['verify'=>true]);

Route::group(['prefix' => 'user','middleware'=>['roles','verified'],'roles'=>['admins','users']], function () {


    Route::get('/profile/{id}','UserPagesController@profile');
    Route::get('/profile/{id}/edit','UserPagesController@profileedit');
    Route::put('/profile/{id}','UserPagesController@profileupdate');
    Route::get('/team/{id}','UserPagesController@myteam');
    Route::get('/changepass/{id}/edit','UserPagesController@editpass');
    Route::put('/changepass/{id}','UserPagesController@updatePassword');
    Route::delete('/teamsusers/{teamId}/{userID}','TeamUserController@deleteTeamUser');
    Route::put('/teamsusers/{teamId}/{userID}','TeamUserController@addTeamUser');
    Route::get('/team/{id}/edit','TeamController@editdata');
    Route::put('/team/{id}','TeamController@updatedata');
    Route::delete('/team/{team}','TeamController@delete');
    Route::put('/money/{user?}','MoneyController@store');
    Route::name('user.')->group( function () {

        Route::resource('stories','UserPagesController')->only(['show','store','edit','update','create']);

    });
    Route::resource('novel','NovelPagesController')->only(['show','index']);

});

Route::group(['prefix' => 'admin','middleware'=>'roles','roles'=>'admins'], function () {

    Route::resource('novels','NavelController');
    Route::get('/changepass/{id}/edit','AdminUsersController@editpass');
    Route::put('/changepass/{id}','AdminUsersController@updatePassword');
    Route::delete('/teamsusers/{teamId}/{userID}','TeamUserController@deleteTeamUser');
    Route::put('/teamsusers/{teamId}/{userID}','TeamUserController@addTeamUser');
    Route::put('/rank/{teamId}/{userID}','TeamController@updaterank');
    Route::put('/unrank/{teamId}/{userID}','TeamController@updateunrank');
    Route::get('/reports','AdminUsersController@teamdata');
    Route::put('/done/{userid}','UserPagesController@changedone');
    Route::put('users/Active/{user}','UserPagesController@activeUser')->name('activeUser');

    Route::post('users/{user}/addMoney', 'AdminUsersController@addMoney')->name('addUserMoney');
    Route::post('users/{user}/delMoney', 'AdminUsersController@delMoney')->name('delUserMoney');
    Route::post('users/{user}/payMoney', 'AdminUsersController@payMoney')->name('payUserMoney');
    Route::get('/money','MoneyController@index')->name('money');
    Route::put('/money/{money}','MoneyController@update');
    Route::delete('/money/{money}','MoneyController@delete')->name('delMoney');
    Route::post('users/Month', 'AdminUsersController@usersMonth')->name('users.Month');
    Route::post('users/{user}/Month', 'AdminUsersController@userMonth')->name('users.user.Month');

    Route::resource('users','AdminUsersController');
    Route::resource('novels','NavelController');
    Route::resource('pays','PayController');
    Route::resource('contacts','ContactController');
    Route::resource('teams','TeamController');
    Route::resource('stories','StoryController');
});
/*
 * index  : Show All Data (GET)
 * create : Show create View (GET)
 * store  : Save data in database (POST)
 * show   : show one data (GET)
 * edit   : show one data for edit  (GET)
 * update : update data and redirect (PUT || PATCH)
 * destroy: Delete Data From database (DELETE)
 *
 * */

app/Team.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

class Team extends Model {
    use LogsActivity;
    protected static $logOnlyDirty = true;

    public $guarded=[];

    public function users(){ return $this->belongsToMany(User::class)->withTimestamps(); }

    public function novels(){ return $this->hasMany(Navel::class); }

}

app/Http/Controllers/TeamController.php
<?php

namespace App\Http\Controllers;

use App\Team;
use App\TeamUser;
use App\User;
use Illuminate\Http\Request;

class TeamController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('team.show')->with('teams',Team::latest()->paginate(50));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('team.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>['required','string']
        ]);
        $team=new Team();
        $team->name=$request->name;
        if($request->chatCode !='') $team->chatCode=$request->chatCode;
        $team->save();
        return redirect(route('teams.show',$team->id));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Team  $team
     * @return \Illuminate\Http\Response
     */
    public function show(Team $team)
    {
        $arr=[];
        foreach ($team->users as $user)
        {
            $arr[]+=$user->id;
        }
        $users=User::whereNotIn('id',$arr)->get();
        return view('team.team')->with(['team'=>$team,'users'=>$users]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Team  $team
     * @return \Illuminate\Http\Response
     */
    public function edit(Team $team)
    {
        return view('team.edit')->with(['team'=>$team]);
    }
    public function editdata(Team $id)
    {
        return view('user.teamedit')->with(['team'=>$id]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Team  $team
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Team $team)
    {
        $request->validate([
            'name'=>['required','string']
        ]);
        $team->update($request->only(['name']));
        $team->update($request->only(['chatCode']));
        return redirect(route('teams.show',$team->id));
    }
    public function updatedata(Request $request, Team $id)
    {
        $id->update($request->only(['name']));
        $id->update($request->only(['chatCode']));
        return back();
    }


    public function updaterank(Request $request,Team $teamId,User $userID)
    {
        $request['team_id']=$teamId->id;
        $request['user_id']=$userID->id;
        $request['rank']=3;

        TeamUser::where($request->only(['user_id','team_id']))->update($request->only(['user_id','team_id','rank']));
        return back();
    }
    public function updateunrank(Request $request,Team $teamId,User $userID)
    {
        $request['team_id']=$teamId->id;
        $request['user_id']=$userID->id;
        $request['rank']=1;
        TeamUser::where($request->only(['user_id','team_id']))->update($request->only(['user_id','team_id','rank']));
        return back();
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Team  $team
     * @return \Illuminate\Http\Response
     */
    public function destroy(Team $team)
    {
        $team->delete();
        return redirect(route('teams.index'));
    }
}

resources/views/team/create.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>اضافة فريق</h1>
@stop

@section('content')
    <form action="{{url('admin/teams')}}" method="POST" role="form">
        @csrf
        <div class="form-group">
            <label for="name">اسم الفريق</label>
            <input type="text" name="name" id="name" class="form-control" placeholder="اسم الفريق" aria-describedby="name">
        </div>
        <div class="form-group">
            <label for="chatCode">كود المحادثات</label>
            <textarea name="chatCode"  cols="30" rows="10" placeholder="كود المحادثات" class="form-control"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">اضافة فريق</button>
    </form>

@stop

resources/views/team/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>تعديل الفريق</h1>
@stop

@section('content')
    <form action="{{url('admin/teams/'.$team->id)}}" method="POST" role="form">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="name">اسم الفريق</label>
            <input type="text" name="name" id="name" class="form-control" value="{{$team->name}}" placeholder="اسم الفريق" aria-describedby="name">
        </div>
        <div class="form-group">
            <label for="chatCode">كود المحادثات</label>
            <textarea name="chatCode"  cols="30" rows="10" class="form-control">{{$team->chatCode}}</textarea>
        </div>
        <button type="submit" class="btn btn-warning">تعديل الفريق</button>
    </form>

@stop

resources/views/team/show.blade.php
@extends('adminlte::page')

@section('content_header')
    <h1>عرض جميع الفرق</h1>
@stop

@section('content')

        <div class="box">
            <div class="box-header with-border">
                <div class="box-tools">
                    <a href="{{route('teams.create')}}" class="label label-primary">اضافة فريق</a>
                </div>
                <!-- /.box-tools -->
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                @if ($teams->count() >0 )
                <table class="table table-responsive">
                    <tr style="border: none">
                        <th>#</th>
                        <th>اسم الفريق</th>
                        <th>اجمالي ارباح الفريق</th>
                        <th>عدد اعضاء الفريق</th>
                    </tr>
                        @foreach ($teams as $team)
                            <tr>
                                <td>{{$team->id}}</td>
                                <td><a href="{{route('teams.show',$team->id)}}">{{$team->name}}</a></td>
                                <td>
                                    <?php $totle=0; ?>
                                        @foreach ($team->novels as $novel)
                                            @foreach ($team->users as $user)
                                                @foreach ($user->stories as $story)
                                                    @if ($story->case==0 && $novel->id==$story->navel_id)
                                                        <?php $totle+=$novel->price; ?>
                                                    @endif
                                                @endforeach
                                            @endforeach
                                        @endforeach
                                    {{number_format($totle)}}
                                </td>
                                <td><div class="dropdown">
                                        <button class="btn btn-secondary dropdown-toggle" type="button" id="triggerId{{$team->id}}"
                                                data-toggle="dropdown" aria-haspopup="true"
                                                aria-expanded="false">
                                            {{count($team->users)}}
                                        </button>
                                        @if (count($team->users)>0)
                                            <div class="dropdown-menu"  aria-labelledby="triggerId{{$team->id}}">
                                                <ol class="">
                                                    @foreach ($team->users as $key=> $user)
                                                        @if ($key>=9)
                                                            @break
                                                        @endif
                                                        <li><a href="{{route('users.show',$user)}}">{{$user->name}}</a></li>
                                                    @endforeach
                                                </ol>
                                            </div>
                                        @endif
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                </table>

                @endif
            </div>
            {{$teams->links()}}
        </div>

@stop

resources/views/team/team.blade.php
@extends('adminlte::page')

@section('content_header')
    <h1>اسم الفريق :  {{$team->name}}</h1>
@stop

@section('content')

  <div class="col-md-8">
      <div class="box">
          <div class="box-header with-border">
              <div class="box-tools pull-right">
                  <!-- Buttons, labels, and many other things can be placed here! -->
                  <!-- Here is a label for example -->
                  <a href="{{url('admin/teams/'.$team->id.'/edit')}}" class="btn btn-warning">تحديث</a>
                  <label for="#">
                      <form action="{{url('admin/teams/'.$team->id)}}" method="POST">
                          @csrf
                          @method('DELETE')
                          <button class="btn btn-danger">حذف</button>
                      </form>
                  </label>
              </div>
              <!-- /.box-tools -->
          </div>
          <div class="box-body">
              @if (count($team->users)>0)
                  <table class="table table-responsive">
                      <tr>
                          <td>اسم العضو</td>
                          <td><i class="fa fa-usd"></i></td>
                          <td>المدير</td>
                          {{--<td>Take All money</td>--}}
                          <td>حذف من الفريق</td>
                      </tr>
                      @foreach ($team->users as $user)
                          <tr>
                              <td>
                                  <a class="col-md-8" href="{{url('admin/users/'.$user->id)}}">{{$user->name}}</a>
                              </td>
                              <td>
                              <?php $money=0;?>
                              @foreach ($team->novels as $novel)
                                  @foreach ($user->stories as $story)
                                      @if ($story->case==0 && $novel->id==$story->navel_id)
                                          <?php $money+=$novel->price; ?>
                                      @endif
                                   @endforeach
                              @endforeach
                                  {{$money}}
                              $
                              </td>
                              <td>
                                  @if (\App\TeamUser::where(['user_id'=>$user->id,'team_id'=>$team->id])->first()->rank!=3)
                                      <form action="{{url('admin/rank/'.$team->id.'/'.$user->id)}}" method="POST">
                                          @csrf
                                          @method('PUT')
                                          <button class="btn btn-success" type="submit">مدير</button>
                                      </form>
                                  @else
                                      <form action="{{url('admin/unrank/'.$team->id.'/'.$user->id)}}" method="POST">
                                          @csrf
                                          @method('PUT')
                                          <button class="btn btn-secondary" type="submit">ازاله مدير</button>
                                      </form>
                                  @endif
                              </td>
                              <td>

                                  <form class="" action="{{url('admin/teamsusers/'.$team->id.'/'.$user->id)}}" method="POST">
                                      @csrf
                                      @method('DELETE')
                                      <button class="btn btn-danger" type="submit">حذف</button>
                                  </form>
                              </td>

                          </tr>
                      @endforeach
                  </table>
              <?php $totle=0; ?>
                  @foreach ($team->novels as $novel)
                      @foreach ($team->users as $user)
                          @foreach ($user->stories as $story)
                              @if ($story->case==0 && $novel->id==$story->navel_id)
                                  <?php $totle+=$novel->price; ?>
                              @endif
                          @endforeach
                      @endforeach
                  @endforeach
                  <small>الاجمالي : {{$totle}}$</small>
                  @else
                  {{"لا يوجد اعضاء"}}
              @endif
                  <hr>
            <h3 class="box-title">روايات</h3>
                  @if (count($team->novels)>0)
                      @foreach ($team->novels as $novel)
                          <a href="{{url('admin/novels/'.$novel->id)}}">{{$novel->name}}</a>
                          <ul class="scrolH">
                              @foreach ($novel->stories as $story)
                                  <li><a href="{{url('admin/stories/'.$story->id)}}">{{$story->storynum}} -{{$story->title}}</a></li>
                              @endforeach
                          </ul>
                      <hr>
                      @endforeach
                  @endif
          </div>
      </div>
  </div>
  <div class="col-md-4">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">اضافة اعضاء</h3>
                </div>
                <div class="box-body scrolH">

                    @foreach ($users as $user)
                        <br>
                            <b class="col-md-9">{{$user->name}}</b>
                            <form action="{{url('admin/teamsusers/'.$team->id.'/'.$user->id)}}" method="POST" class="col-md-3">
                                @csrf
                                @method('PUT')
                                <button class="btn btn-primary" type="submit">اضافة</button>
                            </form>
                        <br>
                    @endforeach
                </div>
            </div>
        </div>

  <div class="clearfix"></div>
@stop

resources/views/team/teamreport.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')
@section('content_header')
    <h1>Report Panel</h1>
@stop

@section('content')

    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Teams</h3>
            <div class="box-tools pull-right">
                <!-- Buttons, labels, and many other things can be placed here! -->
                <!-- Here is a label for example -->
                <a href="{{url('admin/teams/create')}}" class="label label-primary">Add Team</a>
            </div>
            <!-- /.box-tools -->
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            @if (count($teams) >0 )
                <table class="table table-responsive">
                    <tr style="border: none">
                        <th>#</th>
                        <th>Name</th>
                        <th>Count</th>
                    </tr>
                    @foreach ($teams as $team)
                        <tr>
                            <td>{{$team->id}}</td>
                            <td><a href="{{url('admin/teams/'.$team->id)}}">{{$team->name}}</a></td>
                            <td>
                                <?php $totle=0; ?>
                                @foreach ($team->users as $user)
                                    @foreach ($user->stories as $story)
                                        @if ($story->case==0)
                                            <?php $totle+=$story->navel->price;?>
                                        @endif
                                    @endforeach
                                @endforeach
                                {{$totle}}
                            </td>
                        </tr>
                    @endforeach
                </table>
                {{$teams->links()}}
            @endif
        </div>
    </div>

@stop