routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', 'UserPagesController@welcome')->name('welcome');
Route::get('/teams/{story}', 'UserPagesController@teams');

Auth::routes(['verify'=>true]);

Route::group(['prefix' => 'user','middleware'=>['roles','verified'],'roles'=>['admins','users']], function () {


    Route::get('/profile/{id}','UserPagesController@profile');
    Route::get('/profile/{id}/edit','UserPagesController@profileedit');
    Route::put('/profile/{id}','UserPagesController@profileupdate');
    Route::get('/team/{id}','UserPagesController@myteam');
    Route::get('/changepass/{id}/edit','UserPagesController@editpass');
    Route::put('/changepass/{id}','UserPagesController@updatePassword');
    Route::delete('/teamsusers/{teamId}/{userID}','TeamUserController@deleteTeamUser');
    Route::put('/teamsusers/{teamId}/{userID}','TeamUserController@addTeamUser');
    Route::get('/team/{id}/edit','TeamController@editdata');
    Route::put('/team/{id}','TeamController@updatedata');
    Route::delete('/team/{team}','TeamController@delete');
    Route::put('/money/{user?}','MoneyController@store');
    Route::name('user.')->group( function () {

        Route::resource('stories','UserPagesController')->only(['show','store','edit','update','create']);

    });
    Route::resource('novel','NovelPagesController')->only(['show','index']);

});

Route::group(['prefix' => 'admin','middleware'=>'roles','roles'=>'admins'], function () {

    Route::resource('novels','NavelController');
    Route::get('/changepass/{id}/edit','AdminUsersController@editpass');
    Route::put('/changepass/{id}','AdminUsersController@updatePassword');
    Route::delete('/teamsusers/{teamId}/{userID}','TeamUserController@deleteTeamUser');
    Route::put('/teamsusers/{teamId}/{userID}','TeamUserController@addTeamUser');
    Route::put('/rank/{teamId}/{userID}','TeamController@updaterank');
    Route::put('/unrank/{teamId}/{userID}','TeamController@updateunrank');
    Route::get('/reports','AdminUsersController@teamdata');
    Route::put('/done/{userid}','UserPagesController@changedone');
    Route::put('users/Active/{user}','UserPagesController@activeUser')->name('activeUser');

    Route::post('users/{user}/addMoney', 'AdminUsersController@addMoney')->name('addUserMoney');
    Route::post('users/{user}/delMoney', 'AdminUsersController@delMoney')->name('delUserMoney');
    Route::post('users/{user}/payMoney', 'AdminUsersController@payMoney')->name('payUserMoney');
    Route::get('/money','MoneyController@index')->name('money');
    Route::put('/money/{money}','MoneyController@update');
    Route::delete('/money/{money}','MoneyController@delete')->name('delMoney');
    Route::post('users/Month', 'AdminUsersController@usersMonth')->name('users.Month');
    Route::post('users/{user}/Month', 'AdminUsersController@userMonth')->name('users.user.Month');

    Route::resource('users','AdminUsersController');
    Route::resource('novels','NavelController');
    Route::resource('pays','PayController');
    Route::resource('contacts','ContactController');
    Route::resource('teams','TeamController');
    Route::resource('stories','StoryController');
});
/*
 * index  : Show All Data (GET)
 * create : Show create View (GET)
 * store  : Save data in database (POST)
 * show   : show one data (GET)
 * edit   : show one data for edit  (GET)
 * update : update data and redirect (PUT || PATCH)
 * destroy: Delete Data From database (DELETE)
 *
 * */

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Spatie\Activitylog\Traits\LogsActivity;

class User extends Authenticatable implements MustVerifyEmail{
    use Notifiable;
    use LogsActivity;
    protected static $logOnlyDirty = true;

    protected $fillable = [
        'name', 'email', 'password','paymoney','contact_id','contact','pay_id','email_verified_at'
    ];


    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function pay(){ return $this->belongsTo(Pay::class)->withDefault([
        "name"=>"no Pay way"
    ]); }

    public function cont(){ return $this->belongsTo(Contact::class); }
    public function contact(){ return $this->belongsTo(Contact::class)->withDefault([
        "name"=>"no Contact way"
    ]); }

    public function mymoney(){ return $this->hasMany(Money::class); }

    public function teams() { return $this->belongsToMany(Team::class)->withTimestamps(); }

    public function stories() { return $this->hasMany(Story::class); }


    public function roles(){ return $this->belongsToMany(Role::class); }

    public function hasAnyRole($roles){
        if (is_array($roles)){
            foreach ($roles as $role){
                if ($this->hasRole($role)){ return true; }
            }
        }else{
            if ($this->hasRole($roles)){
                return true;
            }
        }
        return false;
    }

    public function hasRole($role){
        if ($this->roles()->where('name',$role)->first()){
            return true;
        }
        return false;
    }

    /**
     * @return mixed
     */
    public function storiesMoney(){

        return $this->stories()->where('case',0)->with('navel')->get()->sum('navel.price');
    }

    public function myAllMoney(){ return $this->mymoney()->where('case',0)->sum('money'); }
    public function oldMoney(){ return $this->mymoney()->where('case',1)->sum('money'); }
    public function moneyMonth(){ return $this->mymoney()->where('case',3)->sum('money'); }
    public function newMoney(){ return $this->mymoney()->where('case',4)->sum('money'); }

    public function GivenMoney(){ return $this->mymoney()->sum('money'); }


    public function userMonth()
    {
        DB::transaction(function (){
            $counter=$this->storiesMoney();
            if ($counter!==0){
                Money::create([
                    'user_id'=>$this->id,
                    'money'=>$counter,
                    'case'=>3
                ]);
            }
            $this->stories()->update(['case' => 1]);
            $this->mymoney()->where('case',4)->update(['case'=>3]);
        });
    }
}

resources/views/user/addstory.blade.php
@extends('ms.master')
@section('content')
    <script src="https://cdn.ckeditor.com/4.11.3/standard/ckeditor.js"></script>

    <form action="{{ route('user.stories.store') }}" method="POST" role="form">
        @csrf

        <div class="form-group">
            <label for="navel_id">الرواية </label>
            <select required class="form-control" name="navel_id" id="navel_id">

            @if (auth()->user()->hasRole('admins'))
                @foreach (\App\Navel::all() as $novel)
                    <option value="{{$novel->id}}">{{$novel->name}}</option>
                @endforeach
            @else
                @foreach ($novales as $novel)
                    <option value="{{$novel->id}}">{{$novel->name}}</option>
                @endforeach
            @endif

            </select>
            @error('navel_id')
            <div class="text-danger"> {{ $message }} </div>
            @enderror
        </div>

        <div class="form-group">
            <label for="storynum">رقم الفصل</label>
            <input required autocomplete="off" type="number" name="storynum" value="{{ old('storynum') }}" id="storynum" class="form-control" placeholder="" aria-describedby="storynum"/>
            @error('storynum')
                <div class="text-danger"> {{ $message }} </div>
            @enderror
        </div>

        <div class="form-group">
            <label for="title">العنوان</label>
            <input required autocomplete="off" type="text" name="title" id="title" value="{{ old('title') }}" class="form-control" placeholder="" aria-describedby="title"/>
            @error('title')
            <div class="text-danger"> {{ $message }} </div>
            @enderror
        </div>

        <div class="form-group">
            <label for="body">محتوي الفصل </label>
            <textarea required class="form-control" name="body" id="editor2" rows="3">{{ old('body') }}</textarea>
        </div>

        <button type="submit" class="btn btn-primary">اضافه الفصل</button>
    </form>
    <script>
        CKEDITOR.replace( 'editor2' );
    </script>
@stop

resources/views/user/myteam.blade.php
@extends('ms.master')
@section('content')

    <div class="col-md-8  float-right">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">معلومات الفر يق</h3>
                <div class="box-tools pull-right">

                    @if ($is_admin==3)
                    <a href="{{url('user/team/'.$team->id.'/edit')}}" class="btn btn-warning text-white">تحديث معلومات الفريق</a>

                    <label for="#">
                        <form action="{{url('user/team/'.$team->id)}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger">حذف الفريق</button>
                        </form>
                    </label>
                    @endif
                </div>
                <!-- /.box-tools -->
            </div>
            <div class="box-body">
                @if (count($team->users)>0)
                    <table class="table">
                        <tr>
                            <td>الاسم</td>
                            <td>المبالغ المطلوب</td>
                            @if ($is_admin==3)
                                <td>الحذف من الفريق</td>
                            @endif
                        </tr>
                        @foreach ($team->users as $user)
                            <tr>
                                <td>
                                    <a class="col-md-8" href="{{url('user/profile/'.$user->id)}}">{{$user->name}}</a>
                                </td>
                                <td>
                                    <?php $money=0;?>
                                        @foreach ($team->novels as $novel)
                                            @foreach ($user->stories as $story)
                                                @if ($story->case==0 && $novel->id==$story->navel_id)
                                                    <?php $money+=$novel->price; ?>
                                                @endif
                                            @endforeach
                                        @endforeach
                                    {{$money}}
                                    $
                                </td>
                                @if ($is_admin==3)
                                <td>
                                    <form class="" action="{{url('user/teamsusers/'.$team->id.'/'.$user->id)}}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger" type="submit">حذف من الفريق</button>
                                    </form>
                                </td>

                                @endif
                            </tr>
                        @endforeach
                    </table>
                    <?php $totle=0; ?>
                    @foreach ($team->novels as $novel)
                        @foreach ($team->users as $user)
                            @foreach ($user->stories as $story)
                                @if ($story->case==0 && $novel->id==$story->navel_id)
                                    <?php $totle+=$novel->price; ?>
                                @endif
                            @endforeach
                        @endforeach
                    @endforeach
                    <div class="text-right">الاجمالي<br>{{$totle}}$</div>
                @else
                    {{"لا يوجد اعضاء في الفريق"}}
                @endif
                <hr>
                <h3 class="box-title">اسم الرواية والفصول </h3>
                @if (count($team->novels)>0)
                    <table class="table">
                        @foreach ($team->novels as $novel)
                            <tr>
                                <td>
                                    <a href="{{url('user/novel/'.$novel->storynum)}}">{{$novel->name}}</a>
                                    <ul class="scrolH">
                                        @foreach ($novel->stories()->orderBy('storynum','desc')->get() as $story)
                                            <li class="col-md-12"><a href="{{url('user/stories/'.$story->id)}}">{{$story->storynum.' - '.$story->title}}</a></li>
                                        @endforeach
                                    </ul>
                                </td>
                            </tr>
                        @endforeach
                    </table>
                @endif
            </div>
        </div>
    </div>
    @if($is_admin==3)
    <div class="col-md-4 float-right">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">اضافة اعضاء للفريق</h3>
            </div>
            <div class="box-body scrolH">
                <table class="table">
                    <tr>
                        <th>الاسم</th>
                        <th>اضافة</th>
                    </tr>
                    @foreach ($users as $user)
                          <tr>
                              <td><a class="font-weight-bold" href="{{url('user/profile/'.$user->id) }}">{{$user->name}}</a></td>
                              <td>
                                  <form  action="{{url('user/teamsusers/'.$team->id.'/'.$user->id)}}" method="POST">
                                      @csrf
                                      @method('PUT')
                                      <button class="btn btn-primary"  type="submit">اضافه</button>
                                  </form>
                              </td>
                          </tr>
                    @endforeach
                </table>

            </div>
        </div>
    </div>
    @endif
    <div class="clearfix"></div>
    @if ($team->chatCode !== null)
        <div class="col-md-12">
            <div class="box box-default">
                <div class="box-header">
                    {{$team->name}} - صندوق المحادثة
                </div>
                <div class="box-body">
                    {!! $team->chatCode !!}
                </div>
            </div>
        </div>
    @endif

@stop

resources/views/user/novel.blade.php
@extends('ms.master')
@section('content')
    <h3 class="text-center">فصول الرواية</h3>
    <nav class="nav">
        <h2 class="text-dark">{{$novel->name}}</h2>
    </nav>
    <ul class="text-right list-unstyled">
        @if (count($stories)>0)
            @foreach ($stories as $story)
                <li class="mt-3"><a href="{{url('user/stories/'.$story->id)}}" style="border:1px solid currentColor;"  class="btn btn-outline-danger">{{$story->storynum." - ".$story->title}}</a></li>
            @endforeach
            @else
            <li class="alert alert-info text-center"><h3>انتظر الفصول قريبا</h3></li>
        @endif
    </ul>
    <hr>
    <a class="btn btn-secondary" href="{{url('user/novel')}}">العودة</a>
    <div class="clearfix"></div>
@stop

resources/views/user/novels.blade.php
@extends('ms.master')
@section('content')
    @isset($urlNoval)
        <h3 class="text-right">
            <a href="{{route('novel.show',$urlNoval->id)}}" class="text-primary">{{$urlNoval->name}}</a>
        </h3>
    @endif
    <h3 class="text-center">الروايات</h3>
    <div class="position-relative text-center">
        @foreach ($novels as $novel)
                <div class=" p-2 card col-md-3 mb-3 mr-3 d-inline-block" style="height:400px;">
                    <div class="row no-gutters position-relative">
                        <div class="col-md-12 overlay-novel">
                            <div class="card-body text-center">
                                <img src="{{asset("uploads/Novel/".$novel->image)}}" class="card-img" height="136" width="100" alt="">
                                <div class="clearfix"></div>
                                <hr>
                                <a class="btn btn-default font-weight-bold text-dark  centeritem w-100" href="{{url('user/novel/'.$novel->id)}}">{{$novel->name}}</a>
                                @if (count($novel->stories()->orderBy('storynum','DESC')->get())>0)
                                    <hr>
                                    @foreach ($novel->stories()->orderBy('storynum','DESC')->get() as $key=> $str)

                                    @if ($key<=4 &&(date_format($str->created_at,'Y-m-d')=== date_format(now(),'Y-m-d')) )
                                        <a href="{{url('user/stories/'.$str->id)}}" @if (date_format($str->created_at,'Y-m-d') === date_format(now(),'Y-m-d')) class="text-success" @endif>{{$str->storynum}} - {{$str->title}}</a>
                                        @if (date_format($str->created_at,'Y-m-d') === date_format(now(),'Y-m-d')) <b class="label rounded label-danger" style="padding:1px"> اليوم</b> @endif
                                        <br>
                                    @endif

                                    @endforeach
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
        @endforeach
    </div>
    <hr>
    {{$novels->links()}}
@stop

resources/views/user/pass.blade.php
@extends('ms.master')

@section('content')
    <h1>تحديث كلمه السر</h1>
    <form action="{{url('user/changepass/'.$user->id)}}" method="POST" role="form">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="newpassword">ادخل كلمه السر الجديدة</label>
            <input required type="password" name="newpassword" id="newpassword" class="form-control" placeholder="newpassword" aria-describedby="newpassword" autocomplete="off">
        </div>
        <button type="submit" class="btn btn-warning">تحديث كلمه السر</button>
    </form>

@stop

resources/views/user/profile.blade.php
@extends('ms.master')

@section('content')

    <div class="col-md-11">
        @if ($myprofile==true)
            <div class="box-tools center-block text-center">
                <a href="{{url('user/changepass/'.optional($user)->id.'/edit')}}" class="btn btn-primary">تغير كلمه السر</a>
                <a href="{{url('user/profile/'.optional($user)->id.'/edit')}}" class="btn btn-warning text-white">تحديث البيانات</a>
                @if (count(optional($user)->stories)>0)
                    @php ($money=optional($user)->mymoney()->where('case',3)->orWhere('case',4)->sum('money'))
                    @if ($money>0 && $myprofile==true)
                        <form action="{{url('user/money/'.optional($user)->id)}}" method="POST" class="d-inline-block">
                            @csrf
                            @method('PUT')
                            <button class="btn btn-info text-white">اطلب مستحقاتك</button>
                        </form>
                        @elseif ($money==0)
                            <button class="btn btn-info text-white" disabled>لا توجد مستحقات</button>
                        @endif
                @endif
            </div>

            <br>
        @endif
        <div class="col-md-5 float-right">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">البيانات الشخصية</h3>
                    <!-- /.box-tools -->
                </div>
                <div class="box-body">
                    الاسم : {{optional($user)->name}}<br>
                    الايمال : {{optional($user)->email}}<br>
                    @if ($pay)
                        طريقة الدفع : {{optional($pay)->name}}<br>
                    @endif
                    @if ($contact)
                        طريقة التواصل : {{optional($contact)->name}}<br>
                    @endif
                </div>
            </div>
        </div>

        <div class="col-md-4 float-right">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">الفصول</h3>
                    <div class="box-tools pull-right"></div>
                </div>
                <div class="box-body">

                    @if (count(optional($user)->stories)>0)
                        <ul class="list-unstyled scrolH">
                            @foreach (optional($user)->stories as $stroy)
                                <li><a href="{{url('user/stories/'.optional($stroy)->id)}}">{{optional($stroy)->title}}</a></li>
                            @endforeach
                        </ul>
                    @else
                        {{"لا يوجد فصول"}}
                    @endif
                </div>
            </div>
        </div>

        <div class="col-md-3  float-right">
            <div class="box box-warning">
                <div class="box-header with-border">
                    <h3 class="box-title">الفريق</h3>
                    <div class="box-tools pull-right"></div>
                </div>
                <div class="box-body">
                    @if (count(optional($user)->teams)>0)
                        <ul class="list-unstyled">
                            @foreach (optional($user)->teams as $team)
                                <li><a href="{{url('admin/teams/'.optional($team)->id)}}">{{optional($team)->name}}</a></li>
                            @endforeach
                        </ul>
                    @else
                        {{"لا يوجد فريق"}}
                    @endif
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    @if ($myprofile==true)

        <div class="info-box bg-info text-white col-md-5 col-sm-12 d-inline-block">
            <span class="info-box-icon"><i class="fa fa-usd"></i></span>
            <div class="info-box-content">
                <span class="info-box-text">مستحقات الشهر</span>
                <span class="info-box-number">{{$nowMoney}}$</span>

            </div><!-- /.info-box-content -->
        </div><!-- /.info-box -->


        <div class="info-box bg-light-blue text-white col-md-5 d-inline-block">
            <span class="info-box-icon"><i class="fa fa-usd"></i></span>
            <div class="info-box-content">
                <span class="info-box-text">مستحقات متراكمة</span>
                <span class="info-box-number">{{$moneyMonth}}$</span>
            </div><!-- /.info-box-content -->
        </div><!-- /.info-box -->

        <div class="info-box bg-red col-md-5 col-sm-12 d-inline-block">
            <span class="info-box-icon"><i class="fa fa-usd"></i></span>
            <div class="info-box-content">
                <span class="info-box-text">مستحقات تحت الطلب</span>
                <span class="info-box-number">{{$userMoney}}$</span>

            </div><!-- /.info-box-content -->
        </div><!-- /.info-box -->

        <div class="info-box bg-success text-white col-md-5 col-sm-12 d-inline-block">
            <span class="info-box-icon"><i class="fa fa-usd"></i></span>
            <div class="info-box-content">
                <span class="info-box-text">مستحقات تم استلامها</span>
                <span class="info-box-number">{{$lastMoney}}$</span>

            </div><!-- /.info-box-content -->
        </div><!-- /.info-box -->

        <div class="clearfix"></div>


        <div class="col-md-6 float-right">
            <div class="box box-danger">
                <div class="box-header with-border">
                    <h3 class="box-title">علميات طلب المستحقات</h3>
                    <div class="box-tools pull-right"></div>
                </div>
                <div class="box-body scrolH">
                    <table class="table table-hover">
                        <tr>
                            <td>المستحقات تحت الطلب</td>
                            <td>تاريخ الطلب</td>
                        </tr>
                        @foreach ($detalisMoney as $des)
                            @if (optional($des)->case===0)
                                <tr>
                                    <td>{{optional($des)->money}}</td>
                                    <td>{{date_format(optional($des)->updated_at,'Y-m-d')}}</td>
                                </tr>
                            @endif
                        @endforeach
                    </table>
                </div>
            </div>
        </div>


        <div class="col-md-6 float-right">
            <div class="box box-danger">
                <div class="box-header with-border">
                    <h3 class="box-title">علميات استلام المستحقات</h3>
                    <div class="box-tools pull-right"></div>
                </div>
                <div class="box-body scrolH">
                    <table class="table table-hover">
                        <tr>
                            <td>المستحقات المستلمه</td>
                            <td>تاريخ التسليم</td>
                        </tr>
                        @foreach ($detalisMoney as $des)
                            @if (optional($des)->case===1)
                            <tr>
                                <td>{{optional($des)->money}}</td>
                                <td>{{date_format(optional($des)->updated_at,'Y-m-d')}}</td>
                            </tr>
                            @endif
                        @endforeach
                    </table>
                </div>
            </div>
        </div>


        <div class="clearfix"></div>

    @endif
@stop

resources/views/user/stories.blade.php
@extends('ms.master')
@section('content')
    <h3 class="text-center">الروايات</h3>
    <nav class="nav">
        @foreach ($novels as $novel)
            <a class="nav-link btn btn-outline-primary ml-1" href="{{url('user/novel/'.$novel->id)}}">{{$novel->name}}</a>
        @endforeach
    </nav>
    {{$novels->links()}}
@stop

resources/views/user/story.blade.php
@extends('ms.master')
@section('content')

    {{--<style>--}}
        {{--.myChapter a{--}}
            {{--color: #3c8dbc !important;--}}
        {{--}--}}
        {{--.myChapter *{--}}
            {{--text-align: center;--}}
        {{--}--}}
    {{--</style>--}}
    <h1 class="text-center">{{$story->storynum}} - {{$story->title}}</h1>
    <h4 class="pull-right"><a href="{{url('user/profile/'.$story->user->id)}}"><i class="fa fa-user"></i> {{$story->user->name}}</a></h4>
    @if ($userid==$story->user_id || \Illuminate\Support\Facades\Auth::user()->hasRole('admins'))
        <a class="btn btn-warning  text-white pull-left" href="{{url('user/stories/'.$story->id.'/edit')}}">تحديث</a>
    @endif
    <div class="clearfix"></div>
    <hr>

    <div class="myChapter" style="direction:rtl;">
        {!! $story->body !!}
    </div>

    <div class="clearfix"></div>
    <hr>
    @if ($nextPage!=-2)
        <div class="pull-left">
            <a href="{{url('user/stories/'.$nextPage)}}" class="btn btn-dark text-white">{{\App\Story::find($nextPage)->storynum}}</a>
        </div>
    @endif
    @if ($backPage!=-2)
        <div class=" pull-right">
            <a href="{{url('user/stories/'.$backPage)}}"  class="btn btn-dark text-white">{{\App\Story::find($backPage)->storynum}}</a>
        </div>
    @endif
    <div class="clearfix"></div>
    <hr>
    <a href="{{url('user/novel/'.$story->navel->id)}}" class="btn btn-secondary">العودة</a>


    <div class="clearfix"></div>
@stop

resources/views/user/storyedit.blade.php
@extends('ms.master')
@section('content')
    <script src="https://cdn.ckeditor.com/4.11.3/standard/ckeditor.js"></script>
    <form action="{{url('user/stories/'.$story->id)}}" method="POST" role="form">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="novel_id">Novel</label>
            <select class="form-control" name="navel_id" id="navel_id">
                @foreach (\App\Team::latest()->get() as $team)
                    @foreach ($team->novels as $novel)
                        <option value="{{$novel->id}}" {{($story->navel_id==$novel->id)?'selected':''}}>{{$novel->name}}</option>
                    @endforeach
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="title">عنوان الفصل </label>
            <input type="text" value="{{$story->title}}" name="title" id="title" class="form-control" placeholder="" aria-describedby="title">
        </div>
        <div class="form-group">
            <label for="storynum">رقم الفصل </label>
            <input required autocomplete="off" value="{{$story->storynum}}" type="number" name="storynum" id="storynum" class="form-control" placeholder="" aria-describedby="storynum">
        </div>
        <div class="form-group">
            <label for="body">المحتوي</label>
            <textarea class="form-control" name="body" id="editor1" rows="3">{{$story->body}}</textarea>
        </div>

        <button type="submit" class="btn btn-warning">التعديل علي الفصل</button>
    </form>
    <script>
        CKEDITOR.replace( 'editor1' );
    </script>
@stop

resources/views/user/teamedit.blade.php
@extends('ms.master')
@section('content')
    <form action="{{url('user/team/'.$team->id)}}" method="POST" role="form">
        @csrf
        @method('PUT')
        <h3>كود الفريق <b class="text-aqua">{{$team->id}}</b> </h3>
        <div class="form-group">
            <label for="name">اسم الفريق</label>
            <input type="text" name="name" id="name" class="form-control" value="{{$team->name}}" placeholder="اسم الفريق" aria-describedby="name">
            <small id="helpId" class="text-muted">اسم الفريق لا يمكن ان يتكرر</small>
        </div>
        <div class="form-group">
            <label for="chatCode">كود المحادثات</label>
            <textarea name="chatCode"  cols="30" rows="10" class="form-control">{{$team->chatCode}}</textarea>
        </div>
        <button type="submit" class="btn btn-warning float-left text-white">تعديل  الفريق</button>
        <a class="btn-secondary btn pull-right" href="{{url('user/team/'.$team->id)}}">العودة</a>
        <div class="clearfix"></div>
    </form>

@stop